### ISSUE TITLE
5v/3v

### ISSUE THREAD

**Issue by flyboy-byte** [No0ne/ps2pico#1]
can i use the sparkfun bi directional logic converter for this project instead of the transistor/diode/resistor converter.

**Comment by No0ne** [comment]
Yes, but you have to use this software: https://github.com/No0ne/ps2x2pico
The code for transistor/diode/resistor converter uses two fixed input pins and two fixed output pins and the code for the bi directional logic converter switches the pin direction of clock and data. Thus the software isn't directly compatible.
