### ISSUE TITLE
Came across this project

### ISSUE THREAD

**Issue by ghhann** [No0ne/ps2pico#4]
Anyway we can get a clear schematic diagram showing all the connections and parts used.

For whatever reason I can't tell by your pictures the layout of the circuit. 

Thank you

**Comment by No0ne** [comment]
Sure, give me a moment!

**Comment by No0ne** [comment]
![ps2pico](https://github.com/No0ne/ps2pico/assets/716129/b0133c44-c170-40f4-a3ad-c545aee92532)
Hope this helps!
